services:
  _defaults:
    autowire: true
    autoconfigure: true

  Krabo\IsotopePackagingSlipBundle\Cron\CheckAvailabilityCron: ~
  Krabo\IsotopePackagingSlipBundle\Cron\ProcessDelayedStatusChangedEventsCron: ~